services:
  - type: web
    name: PULSE.AI
    runtime: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"

  - type: web
    name: Backtester
    runtime: node
    rootDir: web
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: "20"
